apiVersion: v1
kind: Secret
metadata:
  name: deploy-app-secrets
  namespace: hyfy-deploy-app
type: Opaque
data:
  GITHUB_USER: YmlncGF1bGll
  GITHUB_API_TOKEN: Z2hwXzM1bFVWOURocWZHb1dTaDBkaVJzSVFQSUk3YTI2bjJONXNydQ==
  GITHUB_REPOSITORY_NAME: YmlncGF1bGllL0h5RnktcmVsZWFzZXM=
  SECRET_KEY: ZGJlMWQzOTQxZWRiYmJiODQ3YjNhYTQ4ZjgwYjA1OWYyMzY5YjdlNWI3ZjU2NDdlMTdhYjQzNTZkMDgxMWQwNg==
  REACT_APP_API_URL: aHR0cDovLzE3Mi4zMS4yNTUuMTQxOjMwMDg0L2FwaS8=
  GIT_COMMITER_NAME: YmlncGF1bGll
  GIT_COMMITER_EMAIL: YmlncGF1bGllMjNyb0B5YWhvby5jb20=
