name: Deploy application to Docker Hub

on:
  push:
    paths:
      - 'deploy-app/**'
    branches:
      - main
  
jobs:
  handle-docker-hub-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag and push latest image
        run: |
          # change to the directory where the Dockerfile is located
          cd deploy-app && \
           docker build -t aixpand/deploy-app:latest . && \
           docker push aixpand/deploy-app:latest
        shell: bash
      
      - name: Build, tag and push versioned image
        run: |
          # change to the directory where the Dockerfile is located
          VERSION=$(cat deploy-app/ver.txt)
          cd deploy-app && \
           docker pull aixpand/deploy-app:latest && \
           docker tag aixpand/deploy-app:latest aixpand/deploy-app:$VERSION && \
           docker push aixpand/deploy-app:$VERSION
        shell: bash

      - name: Logout from Docker Hub
        run: docker logout